# Generated by Django 2.2.2 on 2019-07-04 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BookingSite.City')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=16)),
                ('l_name', models.CharField(max_length=16)),
                ('m_name', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.EmailField(max_length=320, unique=True)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('STD', 'Standard'), ('DBL', 'Double'), ('DLX', 'Deluxe')], max_length=3)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BookingSite.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BookingSite.Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BookingSite.User')),
            ],
        ),
    ]
